---
- name: Pocket 3 configure sound
  ansible.builtin.copy:
    content: options snd-intel-dspcfg dsp_driver=1
    dest: /etc/modprobe.d/gdp3.conf
    mode: '0644'
    owner: root
    group: root
  become: True

- name: Pocket 3 configure kernel
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: GRUB_CMDLINE_LINUX="mem_sleep_default=s2idle fbcon=rotate:1 video=DSI-1:panel_orientation=right_side_up"
  notify: Pocket 3 update grub
  become: True

- name: Pocket 3 hwdb configure
  ansible.builtin.copy:
    content: |-
      sensor:modalias:acpi:MXC6655*:dmi:*:svnGPD:pnG1621-02:*
       ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1
    dest: /etc/udev/hwdb.d/61-sensor-local.hwdb
    mode: '0644'
    owner: root
    group: root
  notify: Pocket 3 update hwdb
  become: True

- name: Install screen-autorotate-kosmospredanie.yandex.ru
  ansible.builtin.git:
    repo: https://github.com/irqoff/screen-autorotate-kosmospredanie.yandex.ru.git
    dest: "{{ ansible_env['HOME'] }}/.local/share/gnome-shell/extensions/screen-autorotate@kosmospredanie.yandex.ru"
    version: master
    depth: 1

- name: Configure screen-autorotate
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['screen-autorotate@kosmospredanie.yandex.ru']"
    state: present

- name: Configure Caps
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['shift:both_capslock', 'ctrl:nocaps']"
    state: present

- name: Check GetCurrentState
  ansible.builtin.command: gdbus call -e -d org.gnome.Mutter.DisplayConfig -o /org/gnome/Mutter/DisplayConfig
    -m org.gnome.Mutter.DisplayConfig.GetCurrentState
  register: result
  changed_when: no
  when: pocket3_after_reboot | bool

- name: Change scalling
  ansible.builtin.command: gdbus call -e -d org.gnome.Mutter.DisplayConfig -o /org/gnome/Mutter/DisplayConfig
    -m org.gnome.Mutter.DisplayConfig.ApplyMonitorsConfig 1 2 "{{ pocket3_logical_monitors }}" "[]"
  when: pocket3_after_reboot | bool and "'0, 0, 1.25' not in result.stdout"
  changed_when: false
