---
- name: Jammy configuration
  hosts: localhost
  connection: local
  roles:
    - role: python
      tags: python
    - role: vpn
      tags: vpn
      when: enable_vpn
      become: true
    - role: pocket3
      tags: pocket3
      when: pocket3
    - role: common
      tags: common
    - role: docker
      tags: docker
      become: true
    - role: virtualbox
      tags: virtualbox
      become: true
    - role: hashicorp
      tags: hashicorp
      become: true
      when: vpn_enabled
    - role: vscode
      tags: vscode
    - role: bash
      tags: bash
    - role: desktop
      tags: desktop
    - role: linuxbrew
      tags: linuxbrew
